version: '3'

services:
  auth-service:
    #    platform: 'linux/amd64'
    image: 'auth-service:latest'
    container_name: auth-service
    build:
      context: auth-service
      dockerfile: Dockerfile
    depends_on:
      - auth-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=auth_db
      - SPRING_DATASOURCE_PASSWORD=auth_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8085
    expose:
      - "8085"
    ports:
      - "8085:8085"
  auth-db:
    image: 'postgres:15-alpine'
    container_name: auth-db
    environment:
      - POSTGRES_USER=auth_db
      - POSTGRES_PASSWORD=auth_db
      - POSTGRES_DB=auth_db
    volumes:
      - auth_db:/var/lib/postgresql/data
    ports:
      - "5439:5432"
volumes:
  auth_db: