version: '3'

services:
  product-service:
#    platform: 'linux/amd64'
    image: 'product-service:latest'
    container_name: product-service
    build:
      context: product-service
      dockerfile: Dockerfile
    depends_on:
      - product-db
      - cache-redis-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product_db
      - SPRING_DATASOURCE_USERNAME=product_db
      - SPRING_DATASOURCE_PASSWORD=product_db
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SERVER_PORT=8081
      - spring.redis.host=cache-redis-db
      - spring.redis.port=6379
      - REDIS_PASSWORD=eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    expose:
      - "8081"
    ports:
      - "8081:8081"
  product-db:
    image: 'postgres:15-alpine'
    container_name: product-db
    environment:
      - POSTGRES_USER=product_db
      - POSTGRES_PASSWORD=product_db
      - POSTGRES_DB=product_db
    volumes:
      - product_db:/var/lib/postgresql/data
    ports:
      - "5439:5432"
  cache-redis-db:
    image: redis:6.2-alpine
    container_name: cache-redis-db
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache_redis_db:/data
volumes:
  product_db:
  cache_redis_db: